namespace: monitoring-stack

imageRegistry: dkp-harbor.ens-proto.loc/monitoring-stack

storageClass: tatlin-sc

hosts:
  grafana: grafana-demo.ens-proto.loc
  alertmanager: alertmanager.ens-proto.loc
  vmagent: vmagent.ens-proto.loc
  vmselect: vmselect.ens-proto.loc

ingress:
  gatewayName: monitoring-gateway
  gatewayNamespace: monitoring-stack
  ingressGatewaySelector:
    istio: ingressgateway

grafana:
  image: grafana
  tag: "12.0.2"
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
  persistence:
    size: 40Gi
  adminUser: admin
  adminPassword: admin12345 # Лучше вынести в Secret
  db:
    user: grafana
    password: paR2GTM5CUpJd6pd # Лучше вынести в Secret
    database: grafana
    host: postgres # Имя сервиса PostgreSQL
    port: 5432
  datasource:
    name: VictoriaMetrics
    type: prometheus
    url: http://vmselect:8481/select/0/prometheus

postgres:
  image: postgres
  tag: "16"
  superuser:
    username: postgres
    password: SBJUJH4fnbstsvYy
  grafanaDb:
    user: grafana
    password: paR2GTM5CUpJd6pd
    database: grafana
  database: grafana
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 4Gi
  storage:
    size: 50Gi

alertmanager:
  image: alertmanager
  tag: "v0.28.0"
  replicas: 1
  storage:
    size: 10Gi
  config:
    global: {}
    route:
      receiver: blackhole
    receivers:
      - name: blackhole

vmagent:
  image: vmagent
  tag: "v1.124.0"
  replicas: 3
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 2Gi
  config: {}
  remoteWrite:
    enabled: true
    url: http://vminsert:8480/insert/0/prometheus
  externalLabels:
    cluster: monitoring-stack
    env: ens

vmalert:
  image: vmalert
  tag: "v1.124.0"
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  config: {}
  datasourceUrl: "http://vmselect:8481/select/0/prometheus"
  notifierUrl: "http://alertmanager:9093"

victoria:
  vminsert:
    image: vminsert
    tag: "v1.124.0-cluster"
    replicas: 3
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 2
        memory: 8Gi
  vmselect:
    image: vmselect
    tag: "v1.124.0-cluster"
    replicas: 3
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 2
        memory: 8Gi
  vmstorage:
    image: vmstorage
    tag: "v1.124.0-cluster"
    replicas: 3
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 2
        memory: 8Gi
    storage:
      size: 300Gi