apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alertmanager
  namespace: {{ .Values.namespace }}
spec:
  serviceName: alertmanager
  replicas: {{ .Values.alertmanager.replicas }}
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      imagePullSecrets:
        - name: harbor-regcred
      containers:
        - name: alertmanager
          image: {{ printf "%s/%s:%s" .Values.imageRegistry .Values.alertmanager.image .Values.alertmanager.tag }}
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
            - "--storage.path=/alertmanager"
          ports:
            - containerPort: 9093
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
            - name: data
              mountPath: /alertmanager
      volumes:
        - name: config
          configMap:
            name: alertmanager-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.alertmanager.storage.size }}