apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-new
  namespace: {{ .Values.namespace }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: {{ .Values.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}