apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-db-init
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: db-init
          image: postgres:16
          command:
            - /bin/sh
            - -c
            - |
              until pg_isready -h postgres -p 5432; do sleep 2; done
              psql -h postgres -U {{ .Values.postgres.user }} -tc "SELECT 1 FROM pg_roles WHERE rolname='{{ .Values.grafana.db.user }}';" | grep -q 1 || \
              psql -h postgres -U {{ .Values.postgres.user }} -c "CREATE USER {{ .Values.grafana.db.user }} WITH PASSWORD '{{ .Values.grafana.db.password }}';"
              psql -h postgres -U {{ .Values.postgres.user }} -tc "SELECT 1 FROM pg_database WHERE datname='{{ .Values.grafana.db.database }}';" | grep -q 1 || \
              psql -h postgres -U {{ .Values.postgres.user }} -c "CREATE DATABASE {{ .Values.grafana.db.database }} OWNER {{ .Values.grafana.db.user }};"
          env:
            - name: PGPASSWORD
              value: {{ .Values.postgres.password }}