apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ .Values.namespace }}
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: {{ .Values.grafana.datasource.name }}
        type: {{ .Values.grafana.datasource.type | default "prometheus" }}
        access: proxy
        url: {{ .Values.grafana.datasource.url }}
        isDefault: true
        editable: true