apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: {{ .Values.grafana.adminUser | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.grafana.adminPassword | quote }}
  GF_DATABASE_PASSWORD: {{ .Values.grafana.db.password | quote }}