apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-db-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: {{ .Values.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}