apiVersion: v1
kind: Service
metadata:
  name: vmselect-grafana
  namespace: {{ .Values.namespace }}
spec:
  selector:
    statefulset.kubernetes.io/pod-name: vmselect-0
  ports:
    - name: http
      port: 8481
      targetPort: 8481
