apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vmagent
  namespace: {{ .Values.namespace }}
spec:
  serviceName: vmagent
  replicas: {{ .Values.vmagent.replicas }}
  selector:
    matchLabels:
      app: vmagent
  template:
    metadata:
      labels:
        app: vmagent
    spec:
      affinity:
        {{- toYaml .Values.vmagent.affinity | nindent 8 }}
      topologySpreadConstraints:
        {{- toYaml .Values.vmagent.topologySpreadConstraints | nindent 8 }}
      containers:
        - name: vmagent
          image: {{ printf "%s/%s:%s" .Values.imageRegistry .Values.vmagent.image .Values.vmagent.tag }}
          args:
{{- $insertReplicas := .Values.victoria.vminsert.replicas | int }}
{{- range $i := until $insertReplicas }}
            - "-remoteWrite.url=http://vminsert-{{ $i }}:8480/insert/0/prometheus"
{{- end }}
            - "-promscrape.config=/etc/vmagent/prometheus.yaml"
          ports:
            - containerPort: 8429
          resources:
            {{- toYaml .Values.vmagent.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /targets
              port: 8429
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /targets
              port: 8429
            initialDelaySeconds: 30
            periodSeconds: 20
          volumeMounts:
            - name: scrape-config
              mountPath: /etc/vmagent
      volumes:
        - name: scrape-config
          configMap:
            name: vmagent-scrape-config