apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vminsert
  namespace: {{ .Values.namespace }}
spec:
  serviceName: vminsert
  replicas: {{ .Values.victoria.vminsert.replicas }}
  selector:
    matchLabels:
      app: vminsert
  template:
    metadata:
      labels:
        app: vminsert
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - vminsert
                topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: vminsert
      imagePullSecrets:
        - name: harbor-regcred
      containers:
        - name: vminsert
          image: {{ printf "%s/%s:%s" .Values.imageRegistry .Values.victoria.vminsert.image .Values.victoria.vminsert.tag }}
          args:
            - "-storageNode=vmstorage:8400"
          ports:
            - containerPort: 8480
          resources:
            {{- toYaml .Values.victoria.vminsert.resources | nindent 12 }}