apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ .Values.hosts.grafana | quote }}
  gateways:
    - {{ printf "%s/%s" .Values.ingress.gatewayNamespace .Values.ingress.gatewayName }}
  http:
    - route:
        - destination:
            host: grafana
            port:
              number: 3000